import { Helmet } from "react-helmet";
import styled from "styled-components/macro";
import tw from "twin.macro";
import Video from "../components/Video";
import { useEffect, useState } from "react";
import db from "../firebase";

const Home = (props) => {
  const [videos, setVideos] = useState([]);
  useEffect(() => {
    db.collection("videos").onSnapshot((snapshot) =>
      setVideos(snapshot.docs.map((doc) => doc.data()))
    );
  }, []);
  return (
    <>
      <Helmet>
        <title>TikTok React</title>
        <meta name="description" content="Generated by create react app" />
        <link rel="icon" href="/favicon.ico" />
      </Helmet>
      <Container>
        <VideoStack>
          {videos.map((video, i) => (
            <Video
              url={video.url}
              channel={video.channel}
              description={video.description}
              music={video.music}
              likes={video.likes}
              comments={video.comments}
              shares={video.shares}
            />
          ))}
        </VideoStack>
      </Container>
    </>
  );
};

const Container = styled.div`
  ${tw`grid place-items-center bg-black text-white h-screen p-10`}
`;

const VideoStack = styled.div`
  ${tw`h-full w-80 overflow-y-auto snap snap-y scrollbar-hide`}
`;

export default Home;
